"""Update Playlist model

Revision ID: 805aef9ea66d
Revises: 
Create Date: 2024-11-03 19:26:16.890688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805aef9ea66d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('artist_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('music_file_url', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('image_file_url', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('music_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'music', ['music_id'], ['id'])
        batch_op.drop_column('play_count')
        batch_op.drop_column('genre')
        batch_op.drop_column('image_file_url')
        batch_op.drop_column('music_file_url')
        batch_op.drop_column('artist_name')
        batch_op.drop_column('music_name')

    # ### end Alembic commands ###
